server:
  port: 8092
# Freemarker has default values
# classpath =  src/main/resources
#  https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-spring-mvc-template-engines
spring:
  freemarker:
    template-loader-path: file:./../front-end/templates
    suffix: .ftl
